### ISSUE TITLE
[要望]「アタポン計算機」に要求スタミナの概念がほしい

### ISSUE THREAD

**Issue by mikuname** [y-osaru/y-osaru.github.io#7]
求めているのは
・今日から期限日20:59分までの自然回復スタミナを求める
・選択されたライブモードを選び続けた場合に不足するスタミナをスタドリ/ジュエル計算しやすいよう10単位で切り上げて表示
という機能です。

**Comment by y-osaru** [comment]
※通知飛ぶと思いますが、無視してください※
## ○要望に対する考え  
- 現状営業がある為、スタミナはあまり有用な情報とはならない。(営業対応はいくつかの要因で難しい)
- **とはいえどのくらいのスタミナ量が必要かは参考情報としてはあり**
- **計算方法が簡単そうなら実装する。**

## ○計算方法を考えてみる
ざざっと計算方法考える。
- 必要スタミナは通常楽曲消費スタミナ * 倍率 * 通常プレイ回数で求められるので楽。
- 入力スタミナの期間中の自然回復量の計算方法を考える。
	- 入力スタミナが貯まる時間(分)=入力スタミナ * 5
- 期間中の自然回復量は
	期間中の自然回復量 = 期間中に最大まで貯まる回数(※) * 入力スタミナ
	※は期間(分)/入力スタミナが貯まる時間(分)
	→ 計算すると入力スタミナは消える。
	→ 自然回復量は入力スタミナに依存しない？
	→ そうか考えてみりゃ自然回復量は全員フラットなのか。
	→ それを消費できるか/期間中に貯まるか置いておいて。	
	→ スタミナ量が少ない人は貯まる回数が多いから消費の為にインターバルを置いたプレイ方法になる。
	→ 逆にスタミナ量が多い人は貯まる回数が少ないから一気に消費する方法になる。
	→ なるほどな……所持スタミナに依存すると思ってしまっていた。
- という事は、以下の式で良いのでは？
	期間中の自然回復量 = (日数-1) * (24 * 60)/5 + (20 * 60)/5 + 11
	※最終日の20時間と59分(55分なので11回復)
- 必要スタミナ量 - 残り期間の自然回復量 = 不足するスタミナ量(※)
	※1の位を切り上げで0にし、アイテム/ジュエル回復量に合わせる

## ○まとめ
まとめると計算方法はこんな感じ？
- 必要スタミナ量 = 通常楽曲消費スタミナ * 倍率 * 通常プレイ回数
- 自然回復スタミナ量 = (残日数-1) * (24 * 60)/5 + (20 * 60)/5 + 11
	※残り0日の考慮注意
- 不足スタミナ量 = 必要スタミナ量 - 自然回復スタミナ量
	※十の位切り上げ
	※最後の不足は最大スタミナ入れて+してあげるのも良いか？微妙か。

**Comment by y-osaru** [comment]
開始15時だったわ。15:00～24:00と00:00～20:59は分離してあげるか。
一気に計算できそうだけど。

**Comment by y-osaru** [comment]
実装完了。ざっくり計算してみたが合ってそう。
(テストの仕組みを入れる事考えてなかったのダメだよなぁ……)

**Comment by mikuname** [comment]
確認しました。ご対応ありがとうございます。いい感じですね。
