### ISSUE TITLE
[挙動改善]「アタポン計算機」のリザルトが不自然な事がある

### ISSUE THREAD

**Issue by mikuname** [y-osaru/y-osaru.github.io#8]
[現象]
4倍を選択時に、4倍×n回、1倍×2回で出力される事があるが、
これは4倍を選択している状態からみると、不自然です。
(4倍×n回、2倍×1で表示されるのが自然)

原因は把握できていませんが、アイテムに余剰が出ていることが関係しているかもしれません。
再現できる入力値：
days=8, daysPast=6, nowPoint=30000, nowItem=3000, goalPoint=45000

**Comment by y-osaru** [comment]
その挙動は正常(想定した挙動)です。
この計算方法、必ずしも最高効率って訳ではないので。
4倍で回数を計算、切り捨てにより整数になる事で、目標に足りない事があります。
その時は追加で通常プレイをしつつ消費できる倍率でイベント楽曲をやるって仕組みです。
申し訳ないですが、対応不可です。
その数回はアドリブでお願いします。
